---
# handlers file for admin

- name: reload systemd
  systemd:
    daemon_reload: yes

- name: restart grafana-agent
  systemd:
    name: grafana-agent
    state: restarted
    daemon_reload: yes
  when: grafana_agent.enabled | bool

- name: restart node-exporter
  systemd:
    name: node-exporter
    state: restarted
    daemon_reload: yes
  when: node_exporter.enabled | bool

- name: restart promtail
  systemd:
    name: promtail
    state: restarted
    daemon_reload: yes
  when: promtail.enabled | bool

- name: restart monit
  systemd:
    name: monit
    state: restarted
    daemon_reload: yes
  when: monit.enabled | bool