---
# tasks file for polkadot

- name: Run setup tasks
  include_tasks: setup.yaml
  when: not (lifecycle.sync.enabled | default(false) | bool or
            lifecycle.upgrade.enabled | default(false) | bool or
            lifecycle.maintenance.enabled | default(false) | bool)
  tags: ['setup']

- name: Run sync tasks
  include_tasks: sync.yaml
  when: lifecycle.sync.enabled | default(false) | bool
  tags: ['lifecycle', 'sync']

- name: Run upgrade tasks
  include_tasks: upgrade.yaml
  when: lifecycle.upgrade.enabled | default(false) | bool
  tags: ['lifecycle', 'upgrade']

- name: Run maintenance tasks
  include_tasks: maintenance.yaml
  when: lifecycle.maintenance.enabled | default(false) | bool
  tags: ['lifecycle', 'maintenance']

- name: Run health checks
  include_tasks: health_check.yaml
  tags: ['health', 'monitoring']

- name: Configure backups
  include_tasks: backup.yaml
  tags: ['backup', 'setup']
  when: backup_config.enabled | default(true) | bool