---
# tasks file for admin
- name: Include UFW tasks
  include_tasks: ufw.yaml
  when: ansible_os_family == "Debian"

- name: Include Grafana Agent tasks
  include_tasks: grafana_agent.yaml
  when: grafana_agent is defined and grafana_agent.enabled | default(false) | bool

- name: Include Node exporter
  include_tasks: node_exporter.yaml
  when: node_exporter is defined and node_exporter.enabled | default(false) | bool

- name: Include promtail
  include_tasks: promtail.yaml
  when: promtail is defined and promtail.enabled | default(false) | bool

- name: Include Monit tasks
  include_tasks: monit.yaml
  when: monit is defined and monit.enabled | default(false) | bool

- name: Include Teleport tasks
  include_tasks: teleport.yaml
  when: teleport is defined and teleport.enabled | default(false) | bool

- name: Include SSH hardening
  include_tasks: ssh_hardening.yaml