- name: Create node_exporter user
  user:
    name: node_exporter
    system: yes
    shell: /usr/sbin/nologin
    home: /var/lib/node_exporter
    create_home: yes
  tags: ['node_exporter']

- name: Download and extract node_exporter
  unarchive:
    src: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter.version }}/node_exporter-{{ node_exporter.version }}.linux-amd64.tar.gz"
    dest: /tmp
    remote_src: yes
  register: node_exporter_download
  tags: ['node_exporter']

- name: Install node_exporter binary
  copy:
    src: "/tmp/node_exporter-{{ node_exporter.version }}.linux-amd64/node_exporter"
    dest: "{{ node_exporter.install_dir }}/node_exporter"
    mode: '0755'
    remote_src: yes
  notify: restart node-exporter
  tags: ['node_exporter']

- name: Create node_exporter systemd service
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node-exporter.service
    mode: '0644'
  notify: 
    - reload systemd
    - restart node-exporter
  tags: ['node_exporter']

- name: Ensure node_exporter service is enabled and started
  systemd:
    name: node-exporter
    enabled: yes
    state: started
    daemon_reload: yes
  tags: ['node_exporter']