---
- name: Install UFW
  apt:
    name: ufw
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Set UFW default policies
  ufw:
    direction: "{{ item.direction }}"
    policy: "{{ item.policy }}"
  loop:
    - { direction: incoming, policy: "{{ ufw.default_incoming_policy }}" }
    - { direction: outgoing, policy: "{{ ufw.default_outgoing_policy }}" }
  when: ufw.enabled

- name: Configure UFW rules
  ufw:
    rule: "{{ item.rule }}"
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
    from_ip: "{{ item.from | default(omit) }}"
  loop: "{{ ufw.rules }}"
  when: ufw.enabled

- name: Enable UFW
  ufw:
    state: enabled
  when: ufw.enabled
