groups:
  - name: grafana-agent
    rules:
    - alert: GrafanaAgentRequestErrors
      expr: 100 * sum(rate(promtail_request_duration_seconds_count{status_code=~"5..|failed"}[1m])) by (job, route, instance) / sum(rate(promtail_request_duration_seconds_count[1m])) by (job, route, instance) > 10
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: Grafana Agent request errors (instance {{ $labels.instance }})
        description: "The {{ $labels.job }} {{ $labels.route }} is experiencing {{ printf \"%.2f\" $value }}% errors.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

    - alert: GrafanaAgentRequestLatency
      expr: histogram_quantile(0.99, sum(rate(promtail_request_duration_seconds_bucket[5m])) by (le)) > 1
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: Grafana Agent request latency (instance {{ $labels.instance }})
        description: "The {{ $labels.job }} {{ $labels.route }} is experiencing {{ printf \"%.2f\" $value }}s 99th percentile latency.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"