repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json

  - repo: https://github.com/ansible-community/ansible-lint
    rev: v5.0.12
    hooks:
      - id: ansible-lint

  - repo: https://github.com/pre-commit/mirrors-yamllint
    rev: v1.26.3
    hooks:
      - id: yamllint

  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
      - id: black
        language_version: python3