---
- name: Deploy Polkadot Validator
  hosts: localhost
  become: true
  gather_facts: true

  pre_tasks:
  - name: Update apt cache
    apt:
      update_cache: yes
      cache_valid_time: 3600
    tags: always
    when: ansible_os_family == "Debian"

  roles:
    - role: polkadot
      tags: ['polkadot']