---
- name: Deploy Polkadot Validator
  hosts: localhost
  become: true
  gather_facts: true

  pre_tasks:
  - name: Update apt cache
    apt:
      update_cache: yes
      cache_valid_time: 3600
    tags: always
    when: ansible_os_family == "Debian"

  roles:
    - role: admin
      tags: ['admin', 'security', 'monitoring']
    - role: polkadot
      tags: ['polkadot']

  # tasks:
  # - name: Install AppArmor
  #   apt:
  #     name: apparmor
  #     state: present
  #   tags: ['apparmor']

  # - name: Enable AppArmor service
  #   service:
  #     name: apparmor
  #     state: started
  #     enabled: true
  #   tags: ['apparmor']

  # - name: Apply AppArmor profile
  #   copy:
  #     src: files/my_apparmor_profile
  #     dest: /etc/apparmor.d/my_apparmor_profile
  #   notify: Reload AppArmor
  #   tags: ['apparmor']

  # handlers:
  # - name: Reload AppArmor
  #   command: apparmor_parser -r /etc/apparmor.d/my_apparmor_profile
  #   tags: ['apparmor']

  # post_tasks:
  # - name: Check working
  #   polkadot --version
  # polkadot-execute-worker --version
  # polkadot-prepare-worker --version