---
collections:
  - name: community.general
    version: ">=6.0.0"
  - name: ansible.posix
    version: ">=1.5.0"
  - name: community.crypto
    version: ">=2.10.0"
  - name: amazon.aws
    version: ">=6.0.0"
  - name: community.digitalocean
    version: ">=1.24.0"
  - name: netbox.netbox
    version: ">=3.13.0"

roles:
  - src: geerlingguy.docker
    version: "4.2.2"
