---
plugin: community.general.yaml
path_pattern: './hosts/*.yml'
paths:
  - ./hosts

plugin: community.general.netbox
netbox_url: '{{ netbox_url }}'
netbox_token: '{{ netbox_token }}'
group_by:
  - device_roles
  - sites
  - racks
  - tags
query_filters:
  - status: "active"
compose:
  ansible_host: network_interfaces[0].ip_address

plugin: community.general.proxmox
url: '{{ proxmox_url }}'
user: '{{ proxmox_user }}'
password: '{{ proxmox_password }}'
validate_certs: false
want_facts: true
group_prefix: proxmox_
want_proxmox_nodes_ansible_host: true
