groups:
  - name: polkadot_validator
    rules:
      - alert: ValidatorDown
        expr: up{job="polkadot"} == 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Validator metrics down on {{ $labels.instance }}"
          description: "Validator metrics endpoint has been down on {{ $labels.instance }} for more than 5 minutes"

      - alert: ValidatorSyncIssue
        expr: polkadot_sync_target_height - polkadot_sync_current_height > 100
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "Validator sync issue on {{ $labels.instance }}"
          description: "Validator is more than 100 blocks behind the target height for more than 10 minutes"

      - alert: ValidatorMissedBlocks
        expr: increase(polkadot_block_verification_failed_total[1h]) > 5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Validator missing blocks on {{ $labels.instance }}"
          description: "Validator has missed more than 5 blocks in the last hour"

      - alert: ValidatorLowPeers
        expr: substrate_sub_libp2p_peers_count < 10
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "Low peer count on {{ $labels.instance }}"
          description: "Validator has less than 10 peers for more than 10 minutes"

      - alert: ValidatorHighMemoryUsage
        expr: process_resident_memory_bytes / node_memory_MemTotal_bytes * 100 > 90
        for: 15m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage on {{ $labels.instance }}"
          description: "Validator process is using more than 90% of system memory for more than 15 minutes"
