---
- name: Converge
  hosts: all
  become: true
  vars:
    teleport:
      auth_token: "test-token"
      auth_server: "auth.example.com:3025"
    monit:
      checks:
        system:
          enabled: true
    promtail:
      enabled: true
      user: "promtail"
      group: "promtail"
      install_dir: "/usr/local/bin"
      config_dir: "/etc/promtail"
      data_dir: "/var/lib/promtail"
      positions_dir: "/var/lib/promtail/positions"
      version: "2.9.3"
      loki_url: "http://loki.example.com:3100"
    grafana_agent:
      enabled: true
      remote_write:
        - url: "http://prometheus.example.com:9090/api/v1/write"
    node_exporter:
      enabled: true

  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"

  roles:
    - role: admin
